# This rule is not used by the project blanketops-environments-api itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the events.blanketops.dev.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: blanketops-environments
    app.kubernetes.io/part-of: blanketops
    app.kubernetes.io/version: v0.0.1
    environments.blanketops.dev/api-version: v0.1.4
    environments.blanketops.dev/contract-version: v0.2.4
    environments.blanketops.dev/controller-version: v0.4.0
    environments.blanketops.dev/operator-version: v0.7.5

  name: events-githubevent-editor-role
rules:
- apiGroups:
  - events.blanketops.dev
  resources:
  - githubevents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - events.blanketops.dev
  resources:
  - githubevents/status
  verbs:
  - get
