apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: blanketops-environments
    app.kubernetes.io/part-of: blanketops
    app.kubernetes.io/version: v0.0.1
  name: controller-manager
  namespace: system
