apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: blanketops-environments-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/version: v0.0.1
  name: controller-manager
  namespace: system
