apiVersion: environments.blanketops.dev/v1alpha1
kind: Package
metadata:
  labels:
    app.kubernetes.io/name: blanketops-environments
    app.kubernetes.io/part-of: blanketops
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/version: v0.0.1
    environments.blanketops.dev/name: environment-sample
    environments.blanketops.dev/type: dev
    environments.blanketops.dev/api-version: v0.2.9
    environments.blanketops.dev/contract-version: v0.5.4
    environments.blanketops.dev/controller-version: v0.4.3
    environments.blanketops.dev/operator-version: v0.7.8
  name: package-for-kaniko-sample
spec:
  contract:
    enabled: true
    name: for-kaniko-app
    version: v1.2.3
    description: >
      This package contains the API deployment manifests and runtime configuration. #magic___^_^___line
    maintainers:
    - name: Neo
      email: neo@blanketops.online
    repository:
      url: git@github.com:BlanketOps/for-kaniko-app-packages.git
      credentialsSecret: git-ssh-credentials-packages
    diffEnabled: true
    stateRepository:
      url: git@github.com:BlanketOps/for-kaniko-app-state.git
      ref: master
      cloneSecret: git-ssh-credentials-state
      strategy: kustomization
      path: ./clusters/dev
