apiVersion: environments.blanketops.dev/v1alpha1
kind: Package
metadata:
  labels:
    app.kubernetes.io/name: blanketops-environments
    app.kubernetes.io/part-of: blanketops
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/version: v0.0.1
    environments.blanketops.dev/name: environment-sample
    environments.blanketops.dev/type: dev
    environments.blanketops.dev/api-version: v0.1.4
    environments.blanketops.dev/contract-version: v0.1.7
    environments.blanketops.dev/controller-version: v0.2.3
    environments.blanketops.dev/operator-version: v0.0.3
  name: package-for-kaniko-sample
spec:
  contract:
    name: for-kaniko-app
    version: v1.0.0
    enabled: true
    packageName: for-kaniko-app
    packageVersion: v1.2.3
    packageDescription: >
      This package contains the API deployment manifests and runtime configuration. #magic___^_^___line
    packageMaintainers:
    - name: Neo
      email: neo@blanketops.online
    packageRepository:
      url: git@github.com:ntlaletsi70/for-kaniko-app-packages.git
      credentialsSecret: git-ssh-credentials-packages
    packageKappDiff: true
    stateRepo:
      url: git@github.com:ntlaletsi70/for-kaniko-app-state.git
      ref:
        branch: master
      cloneSecret: git-ssh-credentials-state
      strategy: kustomization
      path: ./clusters/dev
