apiVersion: environments.blanketops.dev/v1alpha1
kind: ServiceUnit
metadata:
  labels:
    app.kubernetes.io/name: blanketops-environments
    app.kubernetes.io/part-of: blanketops
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/version: v0.0.1
    environments.blanketops.dev/name: environment-sample
    environments.blanketops.dev/type: dev
    environments.blanketops.dev/api-version: v0.1.4
    environments.blanketops.dev/contract-version: v0.1.7
    environments.blanketops.dev/controller-version: v0.2.3
    environments.blanketops.dev/operator-version: v0.2.1
  name: serviceunit-for-kaniko-web-sample
spec:
  contract:
    type: static
    image: docker.io/nkanyezisolutions/for-kaniko-app:master
    containerPort: 8080
    size: 2
    appType: web
    stackType: nodejs
---
apiVersion: environments.blanketops.dev/v1alpha1
kind: ServiceUnit
metadata:
  labels:
    app.kubernetes.io/name: blanketops-environments
    app.kubernetes.io/part-of: blanketops
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/version: v0.0.1
    environments.blanketops.dev/name: environment-sample
    environments.blanketops.dev/type: dev
    environments.blanketops.dev/api-version: v0.1.4
    environments.blanketops.dev/contract-version: v0.1.7
    environments.blanketops.dev/controller-version: v0.2.3
    environments.blanketops.dev/operator-version: v0.2.1
  name: serviceunit-for-kaniko-worker-sample
spec:
  contract:
    type: build
    buildRef:
      name: build-for-kaniko-sample
    containerPort: 9000
    size: 1
    appType: worker
    stackType: python
