apiVersion: sources.blanketops.dev/v1alpha1
kind: GitRepository
metadata:
  labels:
    app.kubernetes.io/name: blanketops-environments
    app.kubernetes.io/part-of: blanketops
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/version: v0.0.1
    environments.blanketops.dev/name: environment-sample
    environments.blanketops.dev/type: dev
    environments.blanketops.dev/api-version: v0.1.4
    environments.blanketops.dev/contract-version: v0.1.7
    environments.blanketops.dev/controller-version: v0.2.3
    environments.blanketops.dev/operator-version: v0.2.1
  name: gitrepository-for-kaniko-sample
spec:
  contract:
    provider: github
    hookUrl: https://elimination-propecia-meter-strips.trycloudflare.com/
    repository:
      owner: <repository-owner>
      name: <repository-name>
    webhooks:
    - events:
      - push
      - pull_request
