# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/environments.blanketops.dev_environments.yaml
- bases/environments.blanketops.dev_builds.yaml
- bases/environments.blanketops.dev_deployments.yaml
- bases/environments.blanketops.dev_serviceunits.yaml
- bases/environments.blanketops.dev_packages.yaml
- bases/events.blanketops.dev_githubevents.yaml
- bases/networks.blanketops.dev_domains.yaml
- bases/networks.blanketops.dev_routes.yaml
- bases/sources.blanketops.dev_gitrepositories.yaml

# +kubebuilder:scaffold:crdkustomizeresource
# patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch
# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
