name: Make
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.28.0"

      - name: Create kind cluster
        uses: helm/kind-action@v1
        with:
          wait: 120s

      - name: Clean cache
        run: rm -rf bin/

      - name: Make build
        run: make build

      - name: Make validate
        run: make validate

      - name: Make build-installer
        run: make build-installer

      - name: Upload install.yaml
        uses: actions/upload-artifact@v4
        with:
          name: install-manifests
          path: dist/install.yaml
